Feature/develop/task1
VitaliyZekter/csdt2223ki47zektervo14 pull request #1
Opened 2022-09-10 10:40 UTC by VitaliyZekter

Task 1

2022-09-10 17:14 UTC, andrii-s-shpitser-lpnu-ua requested changes

2022-09-10 17:14 UTC, andrii-s-shpitser-lpnu-ua commented on README.md
> -# csdt2223ki47zektervo14
missed "WW" in tag

2022-09-11 10:07 UTC, VitaliyZekter commented on README.md
> -# csdt2223ki47zektervo14
corrected

2022-09-11 12:09 UTC, andrii-s-shpitser-lpnu-ua approved these changes

2022-09-13 17:16 UTC, merged